fix: use proper name for GLTF support env variable
algoo/preview-generator pull request #299
Opened 2022-06-17 12:18 UTC by yedpodtrzitko

## PR Goal

both docs and `.travis.yml` use `GLTF_EXPERIMENTAL_SUPPORT_ENABLED` as the expected name for env variable to enable GLTF support. The code itself however uses `GLTF_EXPERIMENTAL_SUPPORT` (missing `ENABLED` suffix). 

This PR should fix the discrepancy.

## Checkpoints

- [ ] If relevant, **manual tests** have been done to ensure the stability of the whole application and that the involved feature works
- [ ] **Automated tests** covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)
- [ ] The PR or the original issue contains a **short summary of the implemented solution**.

2022-10-10 07:24 UTC, Haskaris requested changes
Thanks for the contribution @yedpodtrzitko 
The variable `GLTF_EXPERIMENTAL_SUPPORT` is also used in [.test.env](https://github.com/algoo/preview-generator/blob/develop/.test.env) and therefore need to be renamed too.
If you can do that we are ready to go!

2022-10-22 06:50 UTC, yedpodtrzitko commented
@Haskaris done

2022-10-24 06:36 UTC, Haskaris approved these changes

2022-10-24 06:37 UTC, Haskaris commented
Everything is good, thank you for your contribution!

2022-10-24 06:38 UTC, merged