fix: do not try to process JSON files
algoo/preview-generator pull request #301
Opened 2022-08-10 16:07 UTC by hrittich

Fixes #300.

2022-08-10 16:08 UTC, raphj commented on preview_generator/preview/builder/image__wand.py
> +        print(mimes)
leftover?

2022-08-10 16:11 UTC, hrittich commented on preview_generator/preview/builder/image__wand.py
> +        print(mimes)
Indeed...

2022-08-10 16:13 UTC, hrittich commented on preview_generator/preview/builder/image__wand.py
> +        print(mimes)
Removed the `print` statement.

2022-08-10 16:14 UTC, raphj commented on preview_generator/preview/builder/image__wand.py
> +        print(mimes)
I'll let Algoo handle the rest :-)

2022-10-10 07:16 UTC, Haskaris commented
Thanks for the contribution @hrittich and thanks for the review @raphj 

Since this PR removes the support to display `JSON` (because ImageMagick doesn't support JSON as an input, therefore nor is Wand), if we merge this PR we also have to modify the [documentation](https://github.com/algoo/preview-generator/blob/develop/doc/supported_mimetypes.rst). If you can do that, we are ready to go!

2022-10-10 07:18 UTC, Haskaris requested changes
As said before, this fix need to also update the [documentation](https://github.com/algoo/preview-generator/blob/develop/doc/supported_mimetypes.rst).

2022-10-10 08:28 UTC, hrittich commented
@Haskaris I have updated the PR to include the update for the documentation.

2022-10-12 06:26 UTC, Haskaris approved these changes

2022-10-12 06:28 UTC, Haskaris commented
Working as a charm! Thank you for the contribution!

2022-10-12 06:29 UTC, merged